build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  CyclomaticComplexity:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  LargeClass:
    active: true
    threshold: 150

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '100']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreLocalVariableDeclaration: true
  WildcardImport:
    active: true
  UnusedPrivateMember:
    active: true
  ReturnCount:
    active: true
    max: 2

naming:
  active: true
  ClassNaming:
    active: true
  FunctionNaming:
    active: true
  VariableNaming:
    active: true
  PackageNaming:
    active: true

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  NullableToStringCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Error
      - Exception
      - RuntimeException
      - Throwable
  PrintStackTrace:
    active: true

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryTemporaryObject:
    active: true
